
drop table user_roles if exists;
drop table roles if exists;
drop table users if exists;

create table if not exists roles (
       id integer generated by default as identity,
        name varchar(20),
        primary key (id)
    );

    create table if not exists user_roles (
       user_id bigint not null,
        role_id integer not null,
        primary key (user_id, role_id)
    );

    create table if not exists users (
       id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        email varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

INSERT INTO users (username, email, password) VALUES ('adminInit','test@admin.de','password');
INSERT INTO users (username, email, password) VALUES ('admin','tes@admin.de','password');


INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_MODERATOR');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');

INSERT INTO user_roles (user_id,role_id) VALUES (1,1);
INSERT INTO user_roles (user_id,role_id) VALUES (2,1);
INSERT INTO user_roles (user_id,role_id) VALUES (2,2);